# src/airpg/runtime/invariants.py
from __future__ import annotations
from typing import List, Tuple, Optional

def check_non_corruption_invariant(
    bare_trace: List[Tuple[Optional[str], str, str]],
    runtime_trace: List[Tuple[Optional[str], str, str]],
) -> None:
    """
    This is a hard assertion that the MinimalRuntime wrapper does not alter
    the fundamental propagation behavior of the core logic it wraps.

    It compares a trace generated by a bare-metal simulation loop with a
    trace generated by the runtime wrapper using the exact same logic.
    The propagation path, recipients, and messages must be identical.
    """
    if bare_trace != runtime_trace:
        raise AssertionError(
            "INVARIANT VIOLATION:\n"
            "MinimalRuntime altered propagation.\n\n"
            f"Bare trace:\n{bare_trace}\n\n"
            f"Runtime trace:\n{runtime_trace}"
        )
